
obj-$(CONFIG_LCD_TRULY_TFT240240_2_E) += lcd-truly_tft240240_2_e.o
obj-$(CONFIG_LCD_TRULY_TFT320320) += lcd-truly_tft320320.o
obj-$(CONFIG_LCD_BYD_8991FTGF) += lcd-8991.o
obj-$(CONFIG_LCD_CV90_M5377_P30) += lcd-mirasol.o
obj-$(CONFIG_LCD_OTM8012A_TFT1P6449) += lcd-otm8012a.o
obj-$(CONFIG_LCD_BYD_9177AA) += lcd-9177aa.o
obj-$(CONFIG_LCD_TRULY_TDO_HD0499K) += lcd-truly_tdo_hd0499k.o
obj-$(CONFIG_LCD_LH155) += lcd-lh155.o
obj-$(CONFIG_LCD_SAMSUNG) += lcd-samsung.o
obj-$(CONFIG_JZ_EPD_V12)	+= epd.o
obj-$(CONFIG_LCD_X163) += lcd-x163.o
obj-$(CONFIG_LCD_ORISE_OTM3201A) += lcd-otm3201a.o
obj-$(CONFIG_LCD_BOE_TFT320320) += lcd-boe_tft320320.o
obj-$(CONFIG_LCD_H160_TFT320320) += lcd-h160_tft320320.o
obj-$(CONFIG_LCD_EDO_E1392AM1) += lcd-edo_e1392am1.o
obj-$(CONFIG_LCD_AUO_H139BLN01) += lcd-auo_h139bln01.o
obj-$(CONFIG_LCD_ARS_NT35350) += lcd-ars_nt35350.o
