
snd-asoc-dma-objs := asoc-dma.o
snd-asoc-aic-objs := asoc-aic.o
snd-asoc-i2s-objs := asoc-i2s.o
snd-asoc-pcm-objs := asoc-pcm.o
snd-asoc-icdc-d1-objs := icodec/icdc_d1.o
snd-asoc-dump-objs := icodec/dump.o

obj-$(CONFIG_SND_ASOC_INGENIC) += snd-asoc-dma.o
obj-$(CONFIG_SND_ASOC_JZ_AIC) += snd-asoc-aic.o
obj-$(CONFIG_SND_ASOC_JZ_AIC_I2S) += snd-asoc-i2s.o
obj-$(CONFIG_SND_ASOC_JZ_ICDC_D1) += snd-asoc-icdc-d1.o
obj-$(CONFIG_SND_ASOC_JZ_PCM) += snd-asoc-pcm.o
obj-$(CONFIG_SND_ASOC_JZ_DUMP_CDC) += snd-asoc-dump.o

snd-soc-dorado-icdc-objs := dorado_icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_DORADO_ICDC) += snd-soc-dorado-icdc.o
snd-soc-newton-icdc-objs := newton_icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_NEWTON_ICDC) += snd-soc-newton-icdc.o
snd-soc-watch-icdc-objs := watch_icdc.o
obj-$(CONFIG_SND_ASOC_INGENIC_WATCH_ICDC) += snd-soc-watch-icdc.o
