obj-$(CONFIG_SLPT) += slpt.o slpt_res.o slpt_key.o slpt_misc.o slpt_map.o slpt_cache.o \
                      malloc_with_name.o argv_creator.o \
                      slpt_method.o slpt_ioctl.o \
                      slpt_power_state.o \
                      slpt_user_configs.o slpt_adc_test.o

obj-$(CONFIG_SLPT_BUILT_IN_FIRMWARE) += slpt_load_self.o
