#
# Makefile for the touchscreen focaltech drivers.
#

obj-$(CONFIG_TOUCHSCREEN_MSG22S) += 	mstar_drv_common.o mstar_drv_ic_fw_porting_layer.o \
					mstar_drv_main.o mstar_drv_platform_interface.o \
					mstar_drv_platform_porting_layer_ingenic.o mstar_drv_self_fw_control.o \
					mstar_drv_ingenic.o mstar_drv_utility_adaption.o
